#!/bin/sh

# Wrapper for mailx, kindly stolen from apticron
#
# Copyright (C) 2002-2005 HEAnet Ltd.
# Copyright (C) 2006-2008 Tiago Bortoletto Vaz and Tassia Camoes Araujo
#
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the author nor the names of the contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# Character set handling differs between the different mailx
# implementations in Debian. Make sure we send proper headers, and a
# text/plain content type.
# 
Mailx() {
        if [ "x`readlink -e /usr/bin/mailx`" = "x/usr/bin/heirloom-mailx" ]
        then
                # heirloom-mailx creates correct headers, but needs help
                # if the terminal charset (LC_CTYPE) is no UTF-8 locale
                if [ -n "$MAIL_FROM" ] ; then
                        /usr/bin/mailx -S ttycharset=utf-8 -r "$MAIL_FROM" "$@"
                else
                        /usr/bin/mailx -S ttycharset=utf-8 "$@"
                fi
        else
                # bsd-mailx/mailutils' mailx don't do character set
                # conversion, but do not support MIME either.
                if [ -n "$MAIL_FROM" ] ; then
                        /usr/bin/mailx -a "MIME-Version: 1.0" \
                                -a "Content-type: text/plain; charset=UTF-8" \
                                -a "Content-transfer-encoding: 8bit" \
                                -a "From: $MAIL_FROM" \
                                "$@"
                else
                        /usr/bin/mailx -a "MIME-Version: 1.0" \
                                -a "Content-type: text/plain; charset=UTF-8" \
                                -a "Content-transfer-encoding: 8bit" \
                                "$@"
                fi
        fi
}




AUDITOR="automated"
MAIL_FROM="lynis@$(cat /etc/yunohost/current_host)"
MAIL_SUBJECT="Lynis report"
MAIL_TO="root@$(cat /etc/yunohost/current_host)"

(
  # http://cisofy.com/documentation/lynis/#cronjobs
  cd /opt/yunohost/lynis && ./lynis -c --auditor "${AUDITOR}" --cronjob
) 2>&1 | Mailx -s "$MAIL_SUBJECT" $MAIL_TO
